name: Deploy .NET Core Web Application to IIS Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: Checkout of the Code
        uses: actions/checkout@v3

      - name: Install .NET Environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.300'

      - name: Verify the .NET Installation
        run: dotnet --version

      - name: Build the Application with .NET
        run: dotnet build --configuration Release

      - name: Publish the Deployment Package in public folder
        run: dotnet publish -c Release -o public

      - name: Create a Artifact using from the public folder
        uses: actions/upload-artifact@v3
        with:
          name: public-folder-to-be-deployed-to-iis
          path: public

      - name: Copy the Files from Work Dir to IIS Directory
        run: |
          iisreset /stop
          Copy-Item ./public/* C:/inetpub/wwwroot/ -Recurse -Force
          iisreset /start
